export const profile = {
  name: 'Yassir Choujai',
  firstName: 'Yassir',
  lastName: 'Choujai',
  role: 'Software Engineer',
  location: 'Tangier, Morocco',
  email: 'yassirchoujai@gmail.com',
  phone: '+212 602 240 933',
  phoneHref: 'tel:+212602240933',
  github: 'https://github.com/yassirchoujai19',
  githubHandle: 'yassirchoujai19',
  linkedin: 'https://www.linkedin.com/in/yassir-choujai-1227b1308/',
  medium: 'https://medium.com/@yassirchoujai',
  roles: ['Software Engineer', 'Full-stack Developer', 'Vue & React Engineer', 'Laravel API Builder'],
  summary:
    'Software engineer passionate about building complete web applications — from REST APIs and data models to the interfaces people actually touch. I learn fast, care about clean, tested code, and bring hands-on experience with React, Next.js, Vue, Nuxt and Laravel to deliver products that are reliable and genuinely pleasant to use.',
}

export const stats = [
  { value: 3, suffix: '', label: 'Companies worked with' },
  { value: 5, suffix: '', label: 'Live products shipped' },
  { value: 25, suffix: '+', label: 'Technologies in my toolbox' },
  { value: 4, suffix: '', label: 'Languages spoken' },
]

export const experience = [
  {
    role: 'Software Engineer',
    company: 'Cosmic Data',
    logo: '/logos/cosmic.png',
    url: 'https://cosmic-data.io',
    place: 'Remote · France',
    period: 'Aug 2025 — Present',
    current: true,
    text: 'Building and evolving production web products end to end — designing user-facing interfaces, wiring them to APIs and data, and improving architecture, performance and reliability across the stack.',
    tags: ['Vue', 'Nuxt', 'TypeScript', 'Tailwind'],
  },
  {
    role: 'Software Developer Intern',
    company: 'Tingis Web',
    logo: '/logos/tingis.jpg',
    place: 'Tangier',
    period: 'May 2025 — Aug 2025',
    text: 'Contributed to a Vue/Nuxt-based product with the team — building and enhancing features on both the front-end and back-end, and deepening my command of modern JavaScript frameworks.',
    tags: ['Vue', 'Nuxt', 'Back-end'],
  },
  {
    role: 'Software Developer Intern',
    company: 'HI5 Group',
    logo: '/logos/hi5.png',
    url: 'https://hi5group.co.uk',
    place: 'Tangier',
    period: 'May 2024 — Jul 2024',
    text: 'Worked alongside the High Five team to develop and improve web apps, strengthening technical skills and adaptability on collaborative projects.',
    tags: ['JavaScript', 'Web apps', 'Teamwork'],
  },
]

export type Project = {
  title: string
  tagline: string
  description: string
  image: string
  live: string
  repo?: string
  stack: string[]
  category: 'React' | 'Vue'
  featured?: boolean
  note?: string
}

const gh = (r: string) => `https://github.com/yassirchoujai19/${r}`

export const projects: Project[] = [
  {
    title: 'Smart Medical Cabinet',
    tagline: 'End-of-year engineering project',
    description:
      'Clinic management platform for admins, doctors and assistants — appointment planning and live waiting room, patient records, consultations and a medication catalogue. Built as a team at ENSI (2026); I engineered the Vue front-end on top of a Laravel + Sanctum API, with i18n, role-based routing, tests and CI/CD.',
    image: '/projects/cabinet.webp',
    live: 'https://smart-medical-cabinet.vercel.app',
    stack: ['Vue 3', 'Pinia', 'Tailwind', 'Vitest', 'Laravel', 'Sanctum', 'MySQL', 'Docker', 'GitHub Actions'],
    category: 'Vue',
    featured: true,
    note: 'Demo: medecin@smc.local / medecin12345',
  },
  {
    title: 'Prepwise',
    tagline: 'AI voice interview platform',
    description:
      'Full-stack, real-time mock-interview app. Candidates talk with an AI voice agent, then receive structured feedback and a score generated by Gemini. Built as my Software Development diploma (PFE) project.',
    image: '/projects/interview.webp',
    live: 'https://ai-voice-interview-platform-pfe.vercel.app',
    repo: gh('ai-voice-interview-platform-PFE-'),
    stack: ['Next.js', 'TypeScript', 'Tailwind', 'Vapi', 'Gemini', 'Firebase'],
    category: 'React',
    featured: true,
  },
  {
    title: 'Stage Manager',
    tagline: 'Internship management workspace',
    description:
      'Role-based internship platform for admins, supervisors and students. Clean service layer, auth guards and an in-memory mock API so the UI is fully usable before the backend ships.',
    image: '/projects/stage.webp',
    live: 'https://stage-management-front.vercel.app',
    repo: gh('stage-management-front'),
    stack: ['Vue 3', 'Pinia', 'Vue Router', 'Axios', 'Vite'],
    category: 'Vue',
    featured: true,
    note: 'Demo: admin@example.com / password',
  },
  {
    title: 'Lovy-Tech Calendar',
    tagline: 'Smart-glasses calendar OS',
    description:
      'Calendar and scheduling system designed for the Lovy-Tech smart-glasses OS — real-time event management, performance tracking and a polished component library.',
    image: '/projects/calendar.webp',
    live: 'https://next-js-calendar-management.vercel.app',
    repo: gh('Next.js-Calendar-Management'),
    stack: ['Next.js', 'TypeScript', 'shadcn/ui', 'Recharts'],
    category: 'React',
    featured: true,
  },
  {
    title: 'LeaveFlow',
    tagline: 'Employee leave management',
    description:
      'HR mini-app to request, approve and track leave with a live dashboard, dark/light themes and persistent state.',
    image: '/projects/leaveflow.webp',
    live: 'https://leave-management-app-sooty.vercel.app',
    repo: gh('Leave-management-app'),
    stack: ['Vue 3', 'Bun', 'Pinia', 'DaisyUI', 'TypeScript'],
    category: 'Vue',
  },
]

export type Tech = { name: string; icon?: string; invert?: boolean }

const t = (name: string, icon?: string, invert = false): Tech => ({ name, icon: icon && `/tech/${icon}.svg`, invert })

export const skillGroups: { title: string; items: Tech[] }[] = [
  { title: 'Languages', items: [t('TypeScript', 'typescript'), t('JavaScript', 'javascript'), t('PHP', 'php'), t('Java', 'java'), t('C#', 'csharp'), t('HTML', 'html5'), t('CSS', 'css3')] },
  { title: 'Front-end', items: [t('React', 'react'), t('Next.js', 'nextjs', true), t('Vue', 'vuejs'), t('Nuxt', 'nuxtjs'), t('Tailwind CSS', 'tailwindcss'), t('Bootstrap', 'bootstrap')] },
  { title: 'Back-end & Data', items: [t('Laravel', 'laravel'), t('REST APIs'), t('MySQL', 'mysql'), t('Firebase', 'firebase'), t('Bun', 'bun')] },
  { title: 'Tooling & Design', items: [t('Git', 'git'), t('Docker', 'docker'), t('GitHub Actions', 'githubactions'), t('Vite', 'vitejs'), t('Vitest', 'vitest'), t('Figma', 'figma'), t('Photoshop', 'photoshop'), t('Illustrator', 'illustrator')] },
]

export const marquee: Tech[] = [
  t('React', 'react'), t('Next.js', 'nextjs', true), t('Vue', 'vuejs'), t('Nuxt', 'nuxtjs'), t('TypeScript', 'typescript'), t('Tailwind CSS', 'tailwindcss'), t('Laravel', 'laravel'), t('PHP', 'php'),
  t('Java', 'java'), t('C#', 'csharp'), t('MySQL', 'mysql'), t('Docker', 'docker'), t('Firebase', 'firebase'), t('Figma', 'figma'), t('Git', 'git'), t('Vite', 'vitejs'),
]

export const education = [
  { title: 'Software Engineering Degree', school: 'ENSI', period: '2025 — Present' },
  { title: 'Software Development Diploma', school: 'CIEL', period: '2023 — 2025' },
  { title: 'English Proficiency', school: 'University of the People', period: '2022 — 2023' },
  { title: 'Baccalaureate in Physics', school: 'King Fahd Ibn Abd Al Aziz', period: '2021 — 2022' },
]

export const strengths = ['Creativity', 'Team Collaboration', 'Continuous Learning', 'Problem-Solving']
export const languages = ['English', 'French', 'Arabic', 'German']
