export const profile = {
  name: 'Yassir Choujai',
  firstName: 'Yassir',
  lastName: 'Choujai',
  role: 'Software Engineer',
  location: 'Tangier, Morocco',
  email: 'yassirchoujai@gmail.com',
  phone: '+212 602 240 933',
  phoneHref: 'tel:+212602240933',
  github: 'https://github.com/yassirchoujai19',
  githubHandle: 'yassirchoujai19',
  roles: ['Front-end Developer', 'Vue & Nuxt Specialist', 'React & Next.js Builder', 'Software Engineering Student'],
  summary:
    'Aspiring software engineer passionate about building web applications and continuously improving my code. I bring a fast learning curve and hands-on experience with JavaScript frameworks — React, Vue and Nuxt — to deliver clear, reliable and user-friendly interfaces.',
}

export const stats = [
  { value: 3, suffix: '', label: 'Companies worked with' },
  { value: 8, suffix: '', label: 'Live projects shipped' },
  { value: 30, suffix: '+', label: 'Public repositories' },
  { value: 4, suffix: '', label: 'Languages spoken' },
]

export const experience = [
  {
    role: 'Front-end Developer',
    company: 'Cosmic Data',
    place: 'Remote · France',
    period: 'Aug 2025 — Present',
    current: true,
    text: 'Designing and improving user-facing web interfaces, crafting seamless, interactive experiences and sharpening front-end architecture across production products.',
    tags: ['Vue', 'Nuxt', 'TypeScript', 'Tailwind'],
  },
  {
    role: 'Software Developer Intern',
    company: 'Tingis Web',
    place: 'Tangier',
    period: 'May 2025 — Aug 2025',
    text: 'Contributed to a Vue/Nuxt-based product with the team — building and enhancing features on both the front-end and back-end, and deepening my command of modern JavaScript frameworks.',
    tags: ['Vue', 'Nuxt', 'Back-end'],
  },
  {
    role: 'Software Developer Intern',
    company: 'HI5 Group',
    place: 'Tangier',
    period: 'May 2024 — Jul 2024',
    text: 'Worked alongside the High Five team to develop and improve web apps, strengthening technical skills and adaptability on collaborative projects.',
    tags: ['JavaScript', 'Web apps', 'Teamwork'],
  },
]

export type Project = {
  title: string
  tagline: string
  description: string
  image: string
  live: string
  repo: string
  stack: string[]
  category: 'React' | 'Vue'
  featured?: boolean
  note?: string
}

const gh = (r: string) => `https://github.com/yassirchoujai19/${r}`

export const projects: Project[] = [
  {
    title: 'Prepwise',
    tagline: 'AI voice interview platform',
    description:
      'Full-stack, real-time mock-interview app. Candidates talk with an AI voice agent, then receive structured feedback and a score generated by Gemini. Built as my final-year (PFE) project.',
    image: '/projects/interview.webp',
    live: 'https://ai-voice-interview-platform-pfe.vercel.app',
    repo: gh('ai-voice-interview-platform-PFE-'),
    stack: ['Next.js', 'TypeScript', 'Tailwind', 'Vapi', 'Gemini', 'Firebase'],
    category: 'React',
    featured: true,
  },
  {
    title: 'Stage Manager',
    tagline: 'Internship management workspace',
    description:
      'Role-based internship platform for admins, supervisors and students. Clean service layer, auth guards and an in-memory mock API so the UI is fully usable before the backend ships.',
    image: '/projects/stage.webp',
    live: 'https://stage-management-front.vercel.app',
    repo: gh('stage-management-front'),
    stack: ['Vue 3', 'Pinia', 'Vue Router', 'Axios', 'Vite'],
    category: 'Vue',
    featured: true,
    note: 'Demo: admin@example.com / password',
  },
  {
    title: 'Lovy-Tech Calendar',
    tagline: 'Smart-glasses calendar OS',
    description:
      'Calendar and scheduling system designed for the Lovy-Tech smart-glasses OS — real-time event management, performance tracking and a polished component library.',
    image: '/projects/calendar.webp',
    live: 'https://next-js-calendar-management.vercel.app',
    repo: gh('Next.js-Calendar-Management'),
    stack: ['Next.js', 'TypeScript', 'shadcn/ui', 'Recharts'],
    category: 'React',
    featured: true,
  },
  {
    title: 'LeaveFlow',
    tagline: 'Employee leave management',
    description:
      'HR mini-app to request, approve and track leave with a live dashboard, dark/light themes and persistent state.',
    image: '/projects/leaveflow.webp',
    live: 'https://leave-management-app-sooty.vercel.app',
    repo: gh('Leave-management-app'),
    stack: ['Vue 3', 'Bun', 'Pinia', 'DaisyUI', 'TypeScript'],
    category: 'Vue',
  },
  {
    title: 'Smart Image Cropper',
    tagline: 'Social-media ready crops',
    description: 'Drop an image and instantly get perfectly cropped versions for every major social platform.',
    image: '/projects/cropper.webp',
    live: 'https://image-croper-test.vercel.app',
    repo: gh('image-croper-test'),
    stack: ['Vue 3', 'Vite', 'Canvas'],
    category: 'Vue',
  },
  {
    title: 'Pinia Tasks',
    tagline: 'State-driven task manager',
    description: 'Task manager with favourites and filters, built to master Pinia stores and the Composition API.',
    image: '/projects/pinia.webp',
    live: 'https://pinia-tasks-eight.vercel.app',
    repo: gh('Pinia-Tasks'),
    stack: ['Vue 3', 'Pinia'],
    category: 'Vue',
  },
  {
    title: 'Random Quotes',
    tagline: 'Daily dose of inspiration',
    description: 'A playful quote generator with smooth transitions and a glassy gradient UI.',
    image: '/projects/quotes.webp',
    live: 'https://random-quote-generator-vuejs.vercel.app',
    repo: gh('RandomQuoteGenerator-vuejs'),
    stack: ['Vue 3', 'CSS'],
    category: 'Vue',
  },
  {
    title: 'Vue To-Do',
    tagline: 'Lightweight productivity',
    description: 'A responsive to-do list to add, complete and clear tasks — simple, fast and focused.',
    image: '/projects/todo.webp',
    live: 'https://vue-to-do-list-beta.vercel.app',
    repo: gh('Vue-To-Do-List'),
    stack: ['Vue', 'JavaScript'],
    category: 'Vue',
  },
]

export const skillGroups = [
  { title: 'Front-end', items: ['HTML', 'CSS', 'JavaScript', 'TypeScript'] },
  { title: 'Frameworks', items: ['React', 'Next.js', 'Vue', 'Nuxt', 'Tailwind CSS', 'Bootstrap'] },
  { title: 'Back-end', items: ['PHP', 'Laravel', 'Java', 'C#'] },
  { title: 'Tools & Design', items: ['Git', 'Figma', 'Photoshop', 'Illustrator'] },
]

export const marquee = [
  'React', 'Next.js', 'Vue', 'Nuxt', 'TypeScript', 'Tailwind CSS', 'Pinia', 'Laravel',
  'PHP', 'Java', 'C#', 'Firebase', 'Figma', 'Git', 'Vite', 'Bun',
]

export const education = [
  { title: 'Software Engineering Degree', school: 'ENSI', period: '2025 — Present' },
  { title: 'Software Development Diploma', school: 'CIEL', period: '2023 — 2025' },
  { title: 'English Proficiency', school: 'University of the People', period: '2022 — 2023' },
  { title: 'Baccalaureate in Physics', school: 'King Fahd Ibn Abd Al Aziz', period: '2021 — 2022' },
]

export const strengths = ['Creativity', 'Team Collaboration', 'Continuous Learning', 'Problem-Solving']
export const languages = ['English', 'French', 'Arabic', 'German']
